### ISSUE TITLE
URL parameter string escaping

### ISSUE THREAD

**Issue by keringar** [IntrepidPig/orca#12]
When I try to submit a self post with & in the text body, everything get's cut off since the & gets treated as a URL parameter delimiter. To fix this, orca needs to convert everything to URL encoded before passing it as a parameter using something like https://rust-lang-nursery.github.io/rust-cookbook/encoding.html#encode-a-string-as-applicationx-www-form-urlencoded.

**Comment by IntrepidPig** [comment]
Oh no, that's an awful issue for this library to have, and it probably affects many more parts of it. Sorry that it's taken so long for me to notice this issue, but I should be able to fix it soon.

**Comment by keringar** [comment]
That's great to hear, I've been working around it by escaping things myself and it hasn't been too big of an issue. Thanks for the library. On Jul 20, 2018 2:55 PM, IntrepidPig <notifications@github.com> wrote:Oh no, that's an awful issue for this library to have, and it probably affects many more parts of it. Sorry that it's taken so long for me to notice this issue, but I should be able to fix it soon.

**Comment by IntrepidPig** [comment]
Ok I've finally fixed this. Please let me know if there's still some funkiness but it should be working fine now. I've only urlencoded the places that might need to be urlencoded, like post titles and text, and not things like usernames, subreddit names, or thing names. Version 0.6.0 is published on crates.io with the fix.
