### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.27`

### ISSUE THREAD

**Issue by ajjaic** [IntrepidPig/orca#9]
If you do not have the dev libraries for openssl, building orca fails.

I was on Debian and a simple `sudo apt install libssl-dev` fixed the problem.

https://github.com/sfackler/rust-openssl/tree/b8fb29db5c246175a096260eacca38180cd77dd0 has information on what to do if you face the same issue on Mac, Windows or Linux.

It might help to add this bit of info to the README.md file.

**Comment by IntrepidPig** [comment]
Thanks for the heads up! I've added a notice at the bottom of the README. I'm not sure if there is anything else I can do to make this any better, so I'll just leave it at that. If you have any suggestions, feel free to let me know.
